### ISSUE TITLE
No improvement of model after 5 epochs

### ISSUE THREAD

**Issue by nanometer34688** [bill9800/speech_separation#14]
Trained using: 
- 2 GPUS 
- batch size=2
- number audio/video files=50k
- epochs=5

I infer on a video that the model has not seen.

The output contains 2 audio files that sound very similar to each other. I cannot distinguish voices between each audio file.

Has anyone got a working model that seems to be doing better than mine?

**Comment by vuthede** [comment]
Hi @nanometer34688 , Have you resolve the problem you reported? if yes, could you share me what you have done, thanks a lot
