### ISSUE TITLE
Not actually an issue, but does it work?

### ISSUE THREAD

**Issue by gttugsuu** [bill9800/speech_separation#2]

**Comment by bill9800** [comment]
Hi, everything in the repository has been tested and run on a device with GPUs.

**Comment by gttugsuu** [comment]
Hi, thanks for response.
Can you please provide some how-to-use instructions? 
Specially around data generating scripts.

**Comment by bill9800** [comment]
Hi, I write a instruction for generating data.
https://github.com/bill9800/speech_separation/blob/master/data/README.md
Welcome to tell me if you have further questions.

**Comment by gttugsuu** [comment]
Thank you very much, i was able to create the dataset.
